spring.application.name=ems-backent
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=Tiger

spring.jpa.hibernate.ddl-auto=update